AWSTemplateFormatVersion: 2010-09-09
Description: Creating Auto Scaling Groups with Cloudformation

Resources:
  supriyaLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-09988af04120b3591
        InstanceType: t2.micro
      LaunchTemplateName: supriyaLaunchTemplate
    
  SupriyaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: SupriyaTargetGroup
      Port: 80
      Protocol: TCP
      VpcId: vpc-02a79ea45d6d06ba7
          
  supriyaLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: supriyaformationLoadBalancer
      Subnets:
        - subnet-0548942d8317fc51a
      Scheme: internet-facing
      Type: network

  supriyaAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: supriyaAutoScalingGroup
      AvailabilityZones:
        - us-east-1b
      MinSize: 1
      MaxSize: 5
      DesiredCapacity: 3
      LaunchTemplate:
        LaunchTemplateId: !Ref supriyaLaunchTemplate
        Version: !GetAtt supriyaLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref SupriyaTargetGroup
     

  supriyaListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref supriyaLoadBalancer
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref SupriyaTargetGroup

  